'use client'

import { ArrowLeft, Bike, CircleDot, Cog, Link2, PackageOpen, Wrench } from 'lucide-react'
import { useState } from 'react'
import { crearCadenaPersonalizada, crearEstrellaPersonalizada, crearKitPersonalizado, crearPinonPersonalizado, crearServicioPersonalizado, type NuevaLineaPersonalizada } from '@/utils/carritoMixto'
import { ACABADOS_ESTRELLA, DIENTES_ESTRELLA, DIENTES_PINON, LONGITUDES_CADENA, NIVELES_SERVICIO, TIPOS_CADENA, calcularCadena, calcularEstrella, calcularPinon, calcularSubtotalKit, precioKitPermitidoMasCercano, precioServicioPorNivel, type AcabadoEstrella } from '@/utils/calculadorasPersonalizadas'

type Calculadora = 'cadena'|'estrella'|'pinon'|'kit'|'servicio'
const dinero=(valor:number)=>`$${valor.toLocaleString('es-MX')}`

function SliderDiscreto({titulo,indice,etiquetas,onChange}:{titulo:string;indice:number;etiquetas:readonly string[];onChange:(indice:number)=>void}){return <div className="fl-calc-slider"><div><span>{titulo}</span><strong>{etiquetas[indice]}</strong></div><input type="range" min={0} max={etiquetas.length-1} step={1} value={indice} onChange={e=>onChange(Number(e.target.value))} aria-label={titulo}/><div className="fl-calc-marks">{etiquetas.map((etiqueta,i)=><button type="button" className={i===indice?'is-active':''} key={etiqueta} onClick={()=>onChange(i)}>{etiqueta}</button>)}</div></div>}
function Selector({valor,opciones,onChange}:{valor:string;opciones:readonly string[];onChange:(v:string)=>void}){return <div className="fl-calc-choice" role="group">{opciones.map(o=><button type="button" key={o} className={o===valor?'is-active':''} onClick={()=>onChange(o)}>{o}</button>)}</div>}
function Precio({valor,detalle,onUsar}:{valor:number;detalle:string;onUsar:()=>void}){return <section className="fl-calc-price"><span>PRECIO</span><strong>{dinero(valor)}</strong><p>{detalle}</p><button type="button" onClick={onUsar}>Agregar a venta</button></section>}

export default function CalculadorasPersonalizadas({onAgregar}:{onAgregar:(linea:NuevaLineaPersonalizada)=>void}){const [activa,setActiva]=useState<Calculadora|null>(null),[aviso,setAviso]=useState('');const usar=(linea:NuevaLineaPersonalizada)=>{onAgregar(linea);setAviso('Agregado a la venta activa.')};const volver=()=>{setActiva(null);setAviso('')};return <section className="fl-calculators">{!activa?<><header><span>HERRAMIENTAS DE MOSTRADOR</span><h2>Productos personalizados</h2><p>Elige un producto para calcular su precio al instante.</p></header><div className="fl-calculator-menu"><Card icon={<Link2/>} titulo="Cadena" texto="Calcula por medida y tipo" onClick={()=>setActiva('cadena')}/><Card icon={<Cog/>} titulo="Estrella" texto="Calcula por dientes" onClick={()=>setActiva('estrella')}/><Card icon={<CircleDot/>} titulo="Piñón" texto="Calcula por dientes" onClick={()=>setActiva('pinon')}/><Card icon={<PackageOpen/>} titulo="Kit de sprocket" texto="Cadena + estrella + piñón" onClick={()=>setActiva('kit')}/><Card icon={<Bike/>} titulo="Servicio de moto" texto="Precio rápido por complejidad" onClick={()=>setActiva('servicio')}/></div></>:<><button type="button" className="fl-calc-back" onClick={volver}><ArrowLeft/>Productos personalizados</button>{activa==='cadena'&&<Cadena onUsar={usar}/>} {activa==='estrella'&&<Estrella onUsar={usar}/>} {activa==='pinon'&&<Pinon onUsar={usar}/>} {activa==='kit'&&<Kit onUsar={usar}/>} {activa==='servicio'&&<Servicio onUsar={usar}/>} {aviso&&<p className="fl-calc-notice" role="status">{aviso}</p>}</>}</section>}
function Card({icon,titulo,texto,onClick}:{icon:React.ReactNode;titulo:string;texto:string;onClick:()=>void}){return <button type="button" className="fl-calculator-card" onClick={onClick}><span>{icon}</span><div><strong>{titulo}</strong><small>{texto}</small></div><b>›</b></button>}

function Cadena({onUsar}:{onUsar:(linea:NuevaLineaPersonalizada)=>void}){const [l,setL]=useState(0),[t,setT]=useState(0);const precio=calcularCadena(l,t),longitud=LONGITUDES_CADENA[l].etiqueta,tipo=TIPOS_CADENA[t].etiqueta;return <article className="fl-calculator"><header><Link2/><div><span>PRODUCTO PERSONALIZADO</span><h2>Cadena</h2></div></header><SliderDiscreto titulo="Longitud" indice={l} etiquetas={LONGITUDES_CADENA.map(x=>x.etiqueta)} onChange={setL}/><h3>Tipo</h3><Selector valor={tipo} opciones={TIPOS_CADENA.map(x=>x.etiqueta)} onChange={v=>setT(TIPOS_CADENA.findIndex(x=>x.etiqueta===v))}/><Precio valor={precio} detalle={`Cadena ${tipo} · ${longitud}`} onUsar={()=>onUsar(crearCadenaPersonalizada(longitud,tipo,precio,crypto.randomUUID()))}/></article>}
function Estrella({onUsar}:{onUsar:(linea:NuevaLineaPersonalizada)=>void}){const [d,setD]=useState(15),[a,setA]=useState<AcabadoEstrella>('Negra');const dientes=DIENTES_ESTRELLA[d],precio=calcularEstrella(dientes,a);return <article className="fl-calculator"><header><Cog/><div><span>PRODUCTO PERSONALIZADO</span><h2>Estrella</h2></div></header><SliderDiscreto titulo="Dientes" indice={d} etiquetas={DIENTES_ESTRELLA.map(String)} onChange={setD}/><h3>Acabado</h3><Selector valor={a} opciones={ACABADOS_ESTRELLA} onChange={v=>setA(v as AcabadoEstrella)}/><Precio valor={precio} detalle={`Estrella ${a.toLowerCase()} · ${dientes} dientes`} onUsar={()=>onUsar(crearEstrellaPersonalizada(dientes,a,precio,crypto.randomUUID()))}/></article>}
function Pinon({onUsar}:{onUsar:(linea:NuevaLineaPersonalizada)=>void}){const [d,setD]=useState(5),dientes=DIENTES_PINON[d],precio=calcularPinon(dientes);return <article className="fl-calculator"><header><CircleDot/><div><span>PRODUCTO PERSONALIZADO</span><h2>Piñón negro</h2></div></header><SliderDiscreto titulo="Dientes" indice={d} etiquetas={DIENTES_PINON.map(String)} onChange={setD}/><Precio valor={precio} detalle={`Piñón negro · ${dientes} dientes`} onUsar={()=>onUsar(crearPinonPersonalizado(dientes,precio,crypto.randomUUID()))}/></article>}
function Kit({onUsar}:{onUsar:(linea:NuevaLineaPersonalizada)=>void}){const [l,setL]=useState(0),[t,setT]=useState(0),[ed,setEd]=useState(15),[a,setA]=useState<AcabadoEstrella>('Negra'),[pd,setPd]=useState(5);const longitud=LONGITUDES_CADENA[l].etiqueta,tipo=TIPOS_CADENA[t].etiqueta,dientesEstrella=DIENTES_ESTRELLA[ed],dientesPinon=DIENTES_PINON[pd],cadena=calcularCadena(l,t),estrella=calcularEstrella(dientesEstrella,a),pinon=calcularPinon(dientesPinon),subtotal=calcularSubtotalKit(cadena,estrella,pinon),precio=precioKitPermitidoMasCercano(subtotal),configCadena={longitud,tipo},configEstrella={dientes:dientesEstrella,color:a},configPinon={dientes:dientesPinon,color:'Negro'};return <article className="fl-calculator"><header><PackageOpen/><div><span>PRODUCTO PERSONALIZADO</span><h2>Kit de sprocket</h2></div></header><section className="fl-kit-section"><h3>Cadena <b>{dinero(cadena)}</b></h3><SliderDiscreto titulo="Longitud" indice={l} etiquetas={LONGITUDES_CADENA.map(x=>x.etiqueta)} onChange={setL}/><Selector valor={tipo} opciones={TIPOS_CADENA.map(x=>x.etiqueta)} onChange={v=>setT(TIPOS_CADENA.findIndex(x=>x.etiqueta===v))}/></section><section className="fl-kit-section"><h3>Estrella <b>{dinero(estrella)}</b></h3><SliderDiscreto titulo="Dientes" indice={ed} etiquetas={DIENTES_ESTRELLA.map(String)} onChange={setEd}/><Selector valor={a} opciones={ACABADOS_ESTRELLA} onChange={v=>setA(v as AcabadoEstrella)}/></section><section className="fl-kit-section"><h3>Piñón <b>{dinero(pinon)}</b></h3><SliderDiscreto titulo="Dientes" indice={pd} etiquetas={DIENTES_PINON.map(String)} onChange={setPd}/></section><div className="fl-kit-totals"><span>Cadena <b>{dinero(cadena)}</b></span><span>Estrella <b>{dinero(estrella)}</b></span><span>Piñón <b>{dinero(pinon)}</b></span><span>Armado kit <b>+$50</b></span><span>Cálculo <b>{dinero(subtotal)}</b></span></div><Precio valor={precio} detalle={`Precio Fast Look · cálculo ${dinero(subtotal)}`} onUsar={()=>onUsar(crearKitPersonalizado(configCadena,configEstrella,configPinon,`${tipo} ${longitud} · ${a} ${dientesEstrella}D · Piñón ${dientesPinon}D`,precio,crypto.randomUUID()))}/></article>}
function Servicio({onUsar}:{onUsar:(linea:NuevaLineaPersonalizada)=>void}){const [nivel,setNivel]=useState(1),[final,setFinal]=useState(50);const cambiar=(i:number)=>{setNivel(i);setFinal(precioServicioPorNivel(i))},etiqueta=NIVELES_SERVICIO[nivel].etiqueta;return <article className="fl-calculator"><header><Wrench/><div><span>SERVICIO PERSONALIZADO</span><h2>Servicio de moto</h2></div></header><SliderDiscreto titulo="Complejidad" indice={nivel} etiquetas={NIVELES_SERVICIO.map(x=>x.etiqueta)} onChange={cambiar}/><div className="fl-service-price"><span>Precio sugerido <b>{dinero(precioServicioPorNivel(nivel))}</b></span><label>Precio final<input type="number" min="0.01" step="0.01" value={final} onChange={e=>setFinal(Math.max(0,Number(e.target.value)))}/></label></div><Precio valor={final} detalle={`Servicio ${etiqueta.toLowerCase()}`} onUsar={()=>{if(final>0)onUsar(crearServicioPersonalizado(etiqueta,final,crypto.randomUUID()))}}/></article>}
